### ISSUE TITLE
Data doesn't get updated reactively

### ISSUE THREAD

**Issue by epaminond** [ecohealthalliance/reactive-table#142]
Starting with 0.5.10 release table doesn't get updated in case underlying collection updates. An update only happens after page reload.

**Comment by aslagle** [comment]
Seems ok in my examples... could you elaborate?

**Comment by epaminond** [comment]
I define reactive-table like this:
```
{{> reactiveTable collection=matchedContacts settings=settings }}
```
And here's the collection helper:
```coffee
matchedContacts: ->
  return [] if Session.equals('searchQ', undefined)
  contacts = Contacts.findByQuery(Session.get 'searchQ')
  $('a.search-tags').data('destroyContactInt', 1) if contacts.count() is 0
  contacts
```

When `searchQ` variable changes helper should return different cursor. It does get fired and runs properly however table still shows old data.

Same code works fine on 0.5.9 release.

**Comment by aslagle** [comment]
Thanks, I'll look into this.

**Comment by brugnara** [comment]
Same problem here.

**Comment by aslagle** [comment]
Try 0.5.12. I have a test for this now :)

**Comment by epaminond** [comment]
0.5.12 works fine for me. Thanks!
