### ISSUE TITLE
Use icons for boolean values

### ISSUE THREAD

**Issue by epaminond** [ecohealthalliance/reactive-table#144]
As `reactive-table` uses font-awesome anyway, I think it would be nice to be able to display `true` boolean values with `fa-check` icon while leaving `false` empty. This can be done now via `fn` setting, but may be that's not difficult to implement.

**Comment by aslagle** [comment]
This might make more sense as an external wrapper that adds `fn` to the fields before they're passed in. I wouldn't want to make it the default, and I'm not sure it's general enough to be worth a separate option to turn on.
